#!/bin/sh
#Script to build up file from smaller part

details() { #Called at end after functions defined


Ofile='../8c_acronyms.html'
gdelete $Ofile

printf '<html><head>' >> $Ofile

printf '\n<title>acronyms</title>' >> $Ofile

printf '\n</head><body>' >> $Ofile

printf '\n<h2 id=8c>acronyms</h2>' >> $Ofile

#certain message if draft
if [ "$1" = "draft" ]; then 
	printf '\n<p>This draft, dated Jul 2022, has not been approved and is subject to modification. DO NOT USE PRIOR TO APPROVAL. (The SWORD Project)</p>' >> $Ofile
fi

#g_toc $Ofile


set -- file1 etc

for arg in "$@"; do
	#printf 'planning to proces file=%s' "$arg"
	cat "${arg}" >> $Ofile
	printf '\n'
done


printf '</body>' >> $Ofile
printf '</html>' >> $Ofile

#w3m $Ofile
} #end main()

g_toc(){ #An option for table of contents
cat >> $1 << Etoc
<table id='toc' border='1'>
<caption>-</caption>
<tr><th>Name</th>
<th>Link</th>
<th>Comment</th></tr>

<tr><td>-</td>
<td><a href="#01">-</a></td>
<td>-</td></tr>
</table>
Etoc
}

details "$@" #call method
